### ISSUE TITLE
Puyo Puyo Tetris: pointer paths are sometimes wrong for Tetris

### ISSUE THREAD

**Issue by Dinopony** [Boffbad/hintMachine#14]
Two distinct reports:
- https://discord.com/channels/731205301247803413/1160627701598658710/1160633983713943613
- https://discord.com/channels/731205301247803413/1160627701598658710/1160652533434437743

**Comment by Dinopony** [comment]
Most likely fixed in 21c373b

**Comment by Dinopony** [comment]
Really fixed in f31ef96 🤞

**Comment by Knuxfan24** [comment]
So it seems like this problem has inverted itself (running from source as of commit https://github.com/CalDrac/hintMachine/commit/48be2436a5b12237767a6a9e729482dc2e07508b), Tetris is working, but putting Solo Arcade into Puyo causes it to disconnect when the round starts and it just cannot reconnect?
![image](https://github.com/CalDrac/hintMachine/assets/10520977/9ade83ba-8c6b-42b5-8ca1-04843aee9f58)
