### ISSUE TITLE
One Finger Death Punch not counting kills properly

### ISSUE THREAD

**Issue by HogeezHoagies** [Boffbad/hintMachine#17]
I assume it's looking at the wrong memory address, because the Kills counter changes arbitrarily and doesn't accurately reflect kills at all.

**Comment by CalDrac** [comment]
Hello,

Sadly, I wasn't able to reproduce,

I used the release 1.0.2 with Steam version

![image](https://github.com/CalDrac/hintMachine/assets/113948164/93a16f09-a31a-48fd-a818-5dab38aaab4f)

**Comment by HogeezHoagies** [comment]
I launch Hint Machine, connect to the Archipelago, launch OFDP, connect Hint Machine to it, load into Story Mode, and it refuses to count kills. I also use the most recent release with the Steam version.
![image](https://github.com/CalDrac/hintMachine/assets/25845660/2ff0a6fe-f604-40a6-8220-a29b2ee458a0)

**Comment by HogeezHoagies** [comment]
Survival Mode doesn't work either. I got 601 kills and it counted none of them.

**Comment by nbrochu** [comment]
For what it's worth, it doesn't work for me either. Fresh install of the game. New campaign, no access to survival yet

**Comment by CalDrac** [comment]
If you can build from sources, I modified to a new pointer address that might be more consistent.

**Comment by nbrochu** [comment]
Works well with the new pointer
