### ISSUE TITLE
Dorfromantik: Started a game, and HintMachine spammed checks

### ISSUE THREAD

**Issue by somebirby** [Boffbad/hintMachine#22]
**HintMachine version**: 1.0.4
**Game**: Dorfromantik
**Game / Emulator version**: Latest/Steam

## Bug description

I opened the game, started a new game, linked HintMachine, went back into the game, and started hearing the "Check Get" sound notification.. a LOT.
Turns out the score gauge got to a huge number (can't recall it exactly, as I quickly closed HintMachine, but it was something like 24XXXX).
Resulted in HintMachine giving me a bunch of unearned hints, ruining a bit of fun.

## Screenshots

![image](https://github.com/CalDrac/hintMachine/assets/16958149/404b4bc7-51c9-45a1-a45a-50af22663a6e)
![image](https://github.com/CalDrac/hintMachine/assets/16958149/a3a2ca7e-a6ec-4f49-a349-ecbd78c084cc)

**Comment by Dinopony** [comment]
Thanks for the report, and sorry it happened.

I don't know if @nbrochu can take a look to check if something's off.

**Comment by Dinopony** [comment]
On my end, I'll take a look into reinforcing global guards to prevent massive hint spamming like this from happening again. Having some bugs on connectors can and will happen, but it should not have such a big impact.

**Comment by nbrochu** [comment]
Yeah I'm going to add more safeguards to the games I added tomorrow. Sorry this happened.

**Comment by nbrochu** [comment]
Resolved in #25
