### ISSUE TITLE
Bust-a-Move 4: Can't connect on BizHawk

### ISSUE THREAD

**Issue by nbrochu** [Boffbad/hintMachine#29]
**HintMachine version**: Dev Branch
**Game**: Bust-a-Move 4 (PAL image)
**Game / Emulator version**: BizHawk 2.9.1 - Nymashock Core

## Bug description

Doesn't connect. Setting breakpoints points to the RAM signature not being found.

## Screenshots

![image](https://github.com/CalDrac/hintMachine/assets/35039/b3a2ffc1-30b4-42ab-9999-498b37f56578)

**Comment by nbrochu** [comment]
Could be that the image wasn't dumped in the same way maybe?

**Comment by nbrochu** [comment]
It was working on the previous version that was on ePSXe though

**Comment by Dinopony** [comment]
The previous version of the connector didn't perform any kind of signature check.
I suspect it could be because we're using a different BIOS?

Inside Bizhawk's "Firmware" window, I see this:

![image](https://github.com/CalDrac/hintMachine/assets/6233833/447247fd-bd9d-4920-8847-11bdb9c88da0)

Also, if you open hex editor and go at the same address, what do you see?

![image](https://github.com/CalDrac/hintMachine/assets/6233833/0595f4af-c3ed-4e57-b634-3eba8e95dfd0)

**Comment by Dinopony** [comment]
A second interesting test would be to comment out the signature check and see if the quest works (and if my guess is right, it should)

**Comment by nbrochu** [comment]
I have to step out. I'll give these a try when I get back.

**Comment by CalDrac** [comment]
Previous version was on ePSXe yeah, maybe we have to redo the thing for BizHawk

**Comment by nbrochu** [comment]
Same BIOS.

Memory region is completely different.
![image](https://github.com/CalDrac/hintMachine/assets/35039/814e3ee8-75a0-4f3b-883c-cb917be0036d)

If I remove the RAM signature code, it connects but then does a bad read and immediately disconnects.

Are we sure this is really for the PAL version of the disc?

**Comment by nbrochu** [comment]
I think the reworked version using the generic BizHawk connector is not using the European version although the instructions say that's what's needed

**Comment by Dinopony** [comment]
I might have worked on the wrong version, I might have used an US image but I'm not certain and cannot verify at the time.
I'll double check tomorrow. Thanks for testing as usual.

**Comment by CalDrac** [comment]
Yeah it works with the US version, I think we'll switch description to US, 60Hz will be better anyway

**Comment by Dinopony** [comment]
Done in 89cd5cf
