### ISSUE TITLE
Columns: Jewels don't increment

### ISSUE THREAD

**Issue by nbrochu** [Boffbad/hintMachine#30]
**HintMachine version**: Dev Branch
**Game**: Columns (World)
**Game / Emulator version**: BizHawk 2.9.1 - Genplus-gx

## Bug description

HintMachine connects successfully but the Jewels don't increment

## Screenshots

![image](https://github.com/CalDrac/hintMachine/assets/35039/d63c7ab0-e1a2-4d96-a5ee-c630aecd86ed)

**Comment by Dinopony** [comment]
Curious, when I play my ROM in arcade mode it looks like this (with a 2p view):

![image](https://github.com/CalDrac/hintMachine/assets/6233833/48518667-a333-4df9-b58b-bf8edcef3e1c)

Could you provide me the hash of your ROM?

**Comment by Dinopony** [comment]
Alright, I pushed a fix on the dev branch (04a7f45), let me know if that fixes it for you.

**Comment by nbrochu** [comment]
I'm afraid this was user error; wrong game version. I think even for emulation-based games, showing supported hashes would be a good practice.

**Comment by Dinopony** [comment]
I'm also starting to think a systematic hash check + having a proper API to handle multiple versions might be useful. I'll start thinking about it.

(Btw don't feel sorry, I fixed a bug on the corrector anyway haha)
