### ISSUE TITLE
MINOR - F-Zero GX: HintMachine claims the 2 quest types were completed on Cup Points completion

### ISSUE THREAD

**Issue by nbrochu** [Boffbad/hintMachine#31]
**HintMachine version**: Dev Branch
**Game**: F-Zero GX
**Game / Emulator version**: Dolphin 5.0-19870

## Bug description

See screenshot. I didn't perform any knockouts, just got enough cup points and the gray text claims the 2 quest types were completed. Only 1 hint point was awarded, so it's a display issue only.

## Screenshots

![image](https://github.com/CalDrac/hintMachine/assets/35039/93d59800-7b71-4eb9-b5f5-275a3c32cba6)

**Comment by Dinopony** [comment]
Thanks, that was a stupid mistake I made lol.
Fixed in b79ae7d
