### ISSUE TITLE
Meteos: Going to red planet after playing a level jumps the score and doesn't accumulate for the level's duration

### ISSUE THREAD

**Issue by nbrochu** [Boffbad/hintMachine#32]
**HintMachine version**: Dev Branch
**Game**: Meteos
**Game / Emulator version**: BizHawk 2.9.1 - MelonDS

## Bug description

Reproduction Steps: Play a non-red planet level in simple mode. For the next level, select the red planet. The score will jump to a higher value right as the level loads. Score is then not accumulated for the whole level. Playing a different level after that works fine.

**Comment by Dinopony** [comment]
When you're talking about score, you are referring to the "Send meteos into space" quest, right?

**Comment by nbrochu** [comment]
Correct

**Comment by Dinopony** [comment]
Found a fix in dd44405, it seems to work for any planet and any number of players now.

**Comment by nbrochu** [comment]
Works perfectly for me now!
