### ISSUE TITLE
Puyo Puyo Tetris: Hint Machine doesn't detect the process is closed / killed

### ISSUE THREAD

**Issue by nbrochu** [Boffbad/hintMachine#33]
**HintMachine version**: Dev Branch
**Game**: Puyo Puyo Tetris
**Game / Emulator version**: Steam

## Bug description

Easy repro: Launch game. Connect with Hint Machine. Alt-F4 game.

## Screenshots

![image](https://github.com/CalDrac/hintMachine/assets/35039/57435346-dc85-4785-bec2-66056a2d886f)

**Comment by Dinopony** [comment]
Fixed in 5b091c5, thanks for the report
