### ISSUE TITLE
Tetris Effect Conected: Add Epic version support

### ISSUE THREAD

**Issue by ChrisFratz** [Boffbad/hintMachine#43]
Would it be possible to add support for the Epic version of Tetris Effect Connected? That's the version I own and I'd rather not buy the game a third time.

**Comment by Dinopony** [comment]
Sadly, I don't own that version so I can't do the porting myself.
Maybe some kind soul who owns this version will take the time to do it 👍

**Comment by CalDrac** [comment]
I don't have it either, I suggest to post in game-suggestions channel and ask if someone could do it in the general channel

**Comment by ChrisFratz** [comment]
If anyone wants to, I'm willing to donate access to my epic account for a bit so it can be worked on.

**Comment by Dinopony** [comment]
That's a kind proposal, I don't think this is allowed by Epic ToS, you can message me on Discord for more details 🙂

**Comment by Dinopony** [comment]
Added in 6d91859 thanks to @christhefox's precious help
