### ISSUE TITLE
Add a generic SNES connector

### ISSUE THREAD

**Issue by Dinopony** [Boffbad/hintMachine#60]
Implement a generic connector for Bizhawk when playing SNES games.

Following the GBA connector implementation could be a good starting point.

Having an hybrid connector using the SNI implementation in Silvris' PR could be an option

**Comment by Silvris** [comment]
The SNI implementation is effectively a generic SNES connector, aside from needing players to connect their emulator to SNI (simple as dragging and dropping, and could even be further automated within HintMachine via subprocesses). With AP likely moving to bundling SNI with every install, I feel like that might just be the better approach.

**Comment by Dinopony** [comment]
Done in c7b849b
