### ISSUE TITLE
911 Operator: Hint Machine doesn't detect the process is closed / killed

### ISSUE THREAD

**Issue by nbrochu** [Boffbad/hintMachine#73]
**HintMachine version**: 1.2.0-rc1
**Game**: 911 Operator
**Game / Emulator version**: Steam

## Bug description

Easy repro: Launch game. Connect with Hint Machine. Alt-F4 game. Probably happening because the game connector is not using BinaryTarget (which automatically check for process presence) and is not doing explicit checks either, while wrapping the RAM reading in try/catch

**Comment by Dinopony** [comment]
Fixed in 03eacb9
