### ISSUE TITLE
Dragon's Crown: No required Vita3K version specified anywhere. Not working with v0.1.9 3443

### ISSUE THREAD

**Issue by nbrochu** [Boffbad/hintMachine#74]
**HintMachine version**: 1.2.0-rc1
**Game**: Dragon's Crown
**Game / Emulator version**: Vita3K v0.1.9 3443

## Bug description

Hint Machine shows as connected but quests don't update. My assumption is I have the wrong Vita3K version, but I can't really tell since the required version is not documented and there is no executable hash checking in place. The connector should probably be updated to use BinaryTarget and also provide image hashing for the supported versions of the game.

**Comment by CalDrac** [comment]
I just remembered I did it on the updated version of the game.

![image](https://github.com/CalDrac/hintMachine/assets/113948164/500d0b1f-850b-4925-95e1-926d1e6e9b07)

Can you try it on the 1.06 version of Dragon's Crown ?
I'll update the description

**Comment by nbrochu** [comment]
Same issue with 1.06
![image](https://github.com/CalDrac/hintMachine/assets/35039/e34712b1-1f4e-4480-8331-096742b4b255)
![image](https://github.com/CalDrac/hintMachine/assets/35039/e7c66728-492b-4621-8f16-6daf194f45b6)

**Comment by CalDrac** [comment]
Okay so weird thing : I Installed the 1.06 patch, but in the menu it shows 1.09 

![image](https://github.com/CalDrac/hintMachine/assets/113948164/22b7a143-9485-444a-8fcc-f01af726f9e1)

**Comment by nbrochu** [comment]
Yup. 1.09 works!

**Comment by nbrochu** [comment]
To be clear, even though the issue was the game update version, should we avoid Vita3K auto-updates going forward?

**Comment by CalDrac** [comment]
I updated the supported version with the Vita3K  v0.1.9 3443 | US ROM 1.09

I added a check on the Vita3K Hash, but since the roms are installed and updated on the console I don't know how to manage them.

**Comment by nbrochu** [comment]
#84
