### ISSUE TITLE
Only 1 quest is displayed in the game selection screen

### ISSUE THREAD

**Issue by nbrochu** [Boffbad/hintMachine#76]
Used to show them all, comma-separated.
![image](https://github.com/CalDrac/hintMachine/assets/35039/d5856804-8865-435e-b710-cc300a09550a)

**Comment by Dinopony** [comment]
That's a regression introduced by one of my recent commits: https://github.com/CalDrac/hintMachine/commit/31ef71a2ecfc8e17e31ec264180246d06264c824

I'll fix it whenever I'm on my PC

**Comment by Dinopony** [comment]
Fixed in a73900f
