### ISSUE TITLE
Pokemon Puzzle Challenge: Cannot connect despite ROM identity being valid (BPNE01)

### ISSUE THREAD

**Issue by nbrochu** [Boffbad/hintMachine#77]
**HintMachine version**: 1.2.0-rc1
**Game**: Pokemon Puzzle Challenge
**Game / Emulator version**: BizHawk 2.9.1 + Gambatte Core

## Bug description

Possible pointer issue? RAM Base Address appears to be 0 while ROM Base Address is populated. Looking at the hex editor confirms the code signature is fine (BPNE01) but when trying to connect, the 6 bytes read are all 0.

## Screenshots

![image](https://github.com/CalDrac/hintMachine/assets/35039/7260836d-e31e-4af3-b67a-2d3e160af493)
![image](https://github.com/CalDrac/hintMachine/assets/35039/7de35aa7-75a9-4798-815c-d0d5b31e3961)

**Comment by Dinopony** [comment]
It worked on my machine, I need to try out other pointers to see which one is the most consistent

**Comment by Dinopony** [comment]
Introduced an alternative set of pointers in 03eacb9 on the `beta` branch, let me know if that fixes it for you

**Comment by nbrochu** [comment]
This one works for me
